-- 001 — 기준 스키마. SQLite 시절의 v9(docs/tease.md §6 + make_shorts.md §5)를 Postgres 로 옮긴 것.
-- 2026-09-06. 데이터는 옮기지 않았다(옮길 데이터가 검증용 1건뿐이었다).
--
-- SQLite 와 달라진 것: 시간은 timestamptz · JSON 은 jsonb · 참/거짓은 boolean · 벡터는 bytea ·
-- id 는 identity. 제약은 전부 DB 가 건다 — Postgres 는 나중에 ALTER 로 바꿀 수 있어서 "새 컬럼엔
-- CHECK 를 못 건다"는 SQLite 시절 규칙이 사라졌다.
--
-- 🔴 이 파일은 적용된 뒤엔 고치지 않는다. 바꿀 게 있으면 002_ 로 덧붙인다(store.py).
-- 🔴 참조 순서: Postgres 는 references 대상이 먼저 있어야 한다. clips 가 question_clusters 를 가리켜서
-- question_clusters 가 clips 보다 앞에 온다.

-- ============================================================
-- sources — 원본 영상
-- ============================================================
create table sources (
    id              integer generated by default as identity primary key,
    title           text        not null,
    -- 🔴 파이프라인 분기의 근거(§4). LECTURE 는 화면을 보지 않는다, FILM 은 본다(2단계).
    content_type    text        not null check (content_type in ('LECTURE', 'FILM')),
    -- 🔴 source_dir 기준 **상대경로**(config.Config.store_source). 절대경로를 넣었다가 레포를 옮기자 전 행이 깨졌다.
    path            text        not null,
    duration_sec    double precision,
    -- 원본을 어디서 가져왔나(URL 또는 설명). 권리 확인이 미해결이라(§9-5) 출처를 잃으면 되찾을 방법이 없다.
    origin          text,
    -- 🔴 원본 중복 유입은 복구 불가한 데이터 오염이다. 파일 내용 sha256. 등록 중엔 'pending:…' 임시값(ingest.begin_source).
    fingerprint     text        not null unique,
    -- 줄거리 / 강연 개요. rank 의 자립성 판단에 들어간다.
    context         text,
    -- STT 언어. null 이면 자동 감지. 값 검증은 코드에서(stt.check_language).
    language        text,
    -- 등록 잡의 상태. RUNNING 은 다운로드·지문 계산 중, 재기동 시 FAILED 로 정리된다(server.serve).
    status          text        not null default 'PENDING'
                                check (status in ('PENDING', 'RUNNING', 'DONE', 'FAILED')),
    error           text,
    -- ---- TEASE (tease §6-3)
    youtube_id      text,       -- 임베드 플레이어·중복 판정. origin 파싱은 취약하다
    chapters        jsonb,      -- yt-dlp 챕터 (tease §5-2)
    caption_source  text        check (caption_source is null or caption_source in ('youtube', 'whisper')),
    channel         text,       -- 채널 횡단 검색의 범위 키 (tease §5-3 b)
    published       boolean     not null default false,   -- /watch 목록 노출 여부
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);

-- ============================================================
-- chunks — 분할 조각. LECTURE 는 소스당 1개(ingest.add_chunk 가 지킨다)
-- ============================================================
-- 사실상 항등이지만 segments 의 부모를 나중에 바꾸면 전 행을 옮겨야 해서 지금 둔다(§5).
create table chunks (
    id          integer generated by default as identity primary key,
    source_id   integer not null references sources (id) on delete cascade,
    idx         integer not null,
    -- 🔴 소스 절대 초. 청크 로컬 시간이 아니다.
    start_sec   double precision not null,
    end_sec     double precision not null,
    -- work_dir 기준 상대경로(config.Config.store_work)
    path        text    not null,
    unique (source_id, idx),
    check (end_sec > start_sec)
);

-- ============================================================
-- utterances — STT/자막 원문 (§4-[1]). 1급 행이라 [3]·[6] 의 인덱스 검증이 SQL 한 방이다
-- ============================================================
create table utterances (
    id              integer generated by default as identity primary key,
    chunk_id        integer not null references chunks (id) on delete cascade,
    idx             integer not null,
    -- 🔴 소스 절대 초.
    start_sec       double precision not null,
    end_sec         double precision not null,
    text            text    not null,
    -- 단어 단위 타임스탬프 [{w, s, e}, …]. [6] 이 발화 중간에서 자를 때 쓴다(tease §5-8).
    words           jsonb,
    -- whisper 의 환각은 avg_logprob 이 낮거나 no_speech_prob 이 높은 구간에서 나온다. 지금 안 모으면 되돌려 볼 수 없다.
    avg_logprob     double precision,
    no_speech_prob  double precision,
    created_at      timestamptz not null default now(),
    unique (chunk_id, idx),
    check (end_sec > start_sec)
);
create index idx_utterances_chunk on utterances (chunk_id);

-- ============================================================
-- segments — 중립 자산 (§3). 기준(run)과 섞지 않는다
-- ============================================================
create table segments (
    id              integer generated by default as identity primary key,
    chunk_id        integer not null references chunks (id) on delete cascade,
    idx             integer not null,
    start_sec       double precision not null,
    end_sec         double precision not null,
    -- LECTURE: 주제 요약 / FILM: 화면 해설. 🔴 기준 중립적으로 써야 한다(§3).
    description     text,
    -- 🔴 발화를 복사하지 않고 **범위로 참조**한다. utterances 가 정본이다. start/end_sec 은 여기서 파생된 비정규화값.
    start_utterance_idx integer not null,
    end_utterance_idx   integer not null,
    describe_model  text,
    -- 실패를 null 로 두면 "아직 안 함"과 구분이 안 된다(§5).
    describe_failed boolean not null default false,
    -- 사람이 손으로 제외한 구간. 🔴 rank 의 'auto' 판정은 여기 쓰지 않는다 — runs.ranked 에만(M0).
    excluded_by     text    check (excluded_by is null or excluded_by in ('human', 'auto')),
    excluded_reason text,
    created_at      timestamptz not null default now(),
    unique (chunk_id, idx),
    check (end_sec > start_sec),
    check (end_utterance_idx >= start_utterance_idx)
);
create index idx_segments_chunk on segments (chunk_id);

-- ============================================================
-- runs — 주관 (뽑기 1회)
-- ============================================================
create table runs (
    id              integer generated by default as identity primary key,
    source_id       integer not null references sources (id) on delete cascade,
    -- 🔴 §6-3: 기준이 비면 그 줄 자체를 프롬프트에서 뺀다. "" 와 null 을 구분 못 하게 되므로 null 만 허용.
    criteria_prompt text    check (criteria_prompt is null or length(trim(criteria_prompt)) > 0),
    -- 🔴 실제로 보낸 프롬프트 전문. [고정] 부분을 튜닝하면 run 끼리 비교가 무의미해지는데 그때 뭘 물었는지 남아야 한다.
    prompt          text,
    -- {raw, ranked: [{idx, score, reason}], excluded: [{idx, reason}]}. 원문(raw)을 함께 남겨야 파싱 실패를 사후에 고친다.
    ranked          jsonb,
    -- 'retrieval' | 'rank' (tease §5-4). null 은 기존 기준 rank.
    route           text    check (route is null or route in ('retrieval', 'rank')),
    status          text    not null default 'PENDING'
                            check (status in ('PENDING', 'RUNNING', 'DONE', 'FAILED')),
    error           text,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);
create index idx_runs_source on runs (source_id);

-- ============================================================
-- question_clusters — 작업 단위 (tease §3-2). 클러스터 하나 = 숏폼 하나
-- ============================================================
-- clips 가 참조하므로 clips 보다 먼저.
create table question_clusters (
    id              integer generated by default as identity primary key,
    source_id       integer not null references sources (id) on delete cascade,
    -- 대표 문장. [집계] 가 LLM 으로 짓거나(tease §5-3 a), 단독 클러스터면 질문 원문. runs.criteria_prompt 로 들어간다.
    canonical_text  text    not null check (length(trim(canonical_text)) > 0),
    -- 🔴 상태 변경은 answers/clusters.transition() 한 곳에서만(update_plan §2-3, D7).
    status          text    not null default 'OPEN'
                            check (status in ('OPEN', 'IN_PROGRESS', 'REVIEW', 'PUBLISHED', 'DECLINED', 'UNANSWERABLE')),
    -- 이 클러스터에 답하려고 띄운 run. 클립이 나오기 전에도 진행 상태를 보여야 한다.
    run_id          integer references runs (id) on delete set null,
    -- UNANSWERABLE 인데 채널 검색이 다른 영상에서 후보를 찾았으면 그 영상(tease §3-4).
    suggested_source_id integer references sources (id) on delete set null,
    created_at      timestamptz not null default now(),
    updated_at      timestamptz not null default now()
);
create index idx_clusters_source_status on question_clusters (source_id, status);

-- ============================================================
-- clips — 완성 클립
-- ============================================================
create table clips (
    id          integer generated by default as identity primary key,
    run_id      integer not null references runs (id) on delete cascade,
    segment_id  integer not null references segments (id) on delete cascade,
    -- 조합 클립에선 봉투(첫 part 시작 ~ 마지막 part 끝). 실제 길이는 total_sec.
    start_sec   double precision not null,
    end_sec     double precision not null,
    score       double precision,
    reason      text,
    -- work_dir 기준 상대경로. 렌더 전엔 null.
    path        text,
    -- 렌더는 편당 재개가 가능해야 한다 — 실패해도 앞 단계를 다시 돌리지 않는다.
    rendered    boolean not null default false,
    -- ---- TEASE (tease §6-3)
    question_cluster_id integer references question_clusters (id) on delete set null,
    -- 🔴 null 이면 시청자에게 보이지 않는다(tease §7-3, I1). 공개 API 는 이 컬럼으로만 거른다.
    published_at    timestamptz,
    total_sec       double precision,
    created_at  timestamptz not null default now(),
    check (end_sec > start_sec)
);
create index idx_clips_run on clips (run_id);
-- 🔴 한 run 안에서 같은 구간으로 클립을 두 번 만들지 않는다. 다시 만들려면 기존 것을 지우고 만든다(replace).
create unique index uq_clips_run_segment on clips (run_id, segment_id);

-- ============================================================
-- clip_parts — 조합 클립의 조각 (tease §5-6). 단일 컷도 part 1개
-- ============================================================
create table clip_parts (
    id                  integer generated by default as identity primary key,
    clip_id             integer not null references clips (id) on delete cascade,
    ordinal             integer not null,
    segment_id          integer references segments (id) on delete set null,
    start_sec           double precision not null,
    end_sec             double precision not null,
    -- 🔴 초는 여기서 파생된다. LLM 이 말한 초가 아니라 utterances(단어 단위 포함)에서 되찾은 값.
    start_utterance_idx integer not null,
    end_utterance_idx   integer not null,
    unique (clip_id, ordinal),
    check (end_sec > start_sec),
    check (end_utterance_idx >= start_utterance_idx)
);

-- ============================================================
-- clip_reviews — 품질 판정 (§11). append-only, 읽을 때 최신 행
-- ============================================================
create table clip_reviews (
    id          integer generated by default as identity primary key,
    clip_id     integer not null references clips (id) on delete cascade,
    verdict     text    not null check (verdict in ('OK', 'NG')),
    note        text,
    -- 'human' | 'llm' (tease §5-7). judge 의 판정도 여기 쌓인다.
    reviewer    text    not null default 'human' check (reviewer in ('human', 'llm')),
    created_at  timestamptz not null default now()
);
create index idx_clip_reviews_clip on clip_reviews (clip_id);

-- ============================================================
-- stage_calls — 계측 (§12: 예외 없이 전 단계 기록)
-- ============================================================
-- 🔴 LLM 호출만이 아니라 **모든 단계**를 기록한다. 이 파이프라인의 실제 제약은 비용이 아니라 시간이다(§7).
-- 세 참조가 전부 nullable 인 이유: [3] 주제 분할은 run 이 생기기 전에 돌고 segment 도 아직 없다.
-- on delete set null: 소스를 지워도 비용/시간 이력은 남아야 한다.
create table stage_calls (
    id              integer generated by default as identity primary key,
    source_id       integer references sources (id) on delete set null,
    run_id          integer references runs (id) on delete set null,
    segment_id      integer references segments (id) on delete set null,
    -- 오타가 나면 집계가 조용히 쪼개지므로 값을 고정한다. 비-LLM 단계(chunk·stt·render·download·preview)는 model·토큰이 null.
    stage           text    not null check (stage in
                            ('ping', 'chunk', 'stt', 'segment', 'describe', 'rank', 'cut', 'render',
                             'caption', 'embed', 'retrieve', 'cluster', 'judge', 'classify', 'download', 'preview')),
    model           text,
    input_tokens    integer,
    output_tokens   integer,
    -- 🔴 사고 토큰은 출력 단가로 과금된다. 비용이 튀는 지점이라 따로 센다(§7).
    thinking_tokens integer,
    -- candidates 에 thoughts 가 이미 포함되는지가 SDK/모델마다 분명하지 않아 total 을 같이 둔다.
    total_tokens    integer,
    cached_tokens   integer,
    latency_ms      integer,
    -- 그 단계를 무엇으로 돌렸나. stt 면 initial_prompt·vad, LLM 이면 온도 같은 것. 없으면 재현이 안 된다.
    params          jsonb,
    error           text,
    created_at      timestamptz not null default now()
);
create index idx_stage_calls_source on stage_calls (source_id);
create index idx_stage_calls_run    on stage_calls (run_id);
create index idx_stage_calls_stage  on stage_calls (stage);

-- ============================================================
-- questions — 시청자가 적은 질문 원문 (tease §3-1)
-- ============================================================
-- 🔴 등록은 insert 만이다 — 임베딩도 LLM 도 부르지 않는다(update_plan D11). 묶기는 크리에이터의 [집계].
create table questions (
    id          integer generated by default as identity primary key,
    -- 어느 영상을 보다가 물었나. 답이 다른 영상에 있어도 "물은 곳"은 여기다.
    source_id   integer not null references sources (id) on delete cascade,
    text        text    not null check (length(trim(text)) > 0),
    -- 익명 시청자 쿠키 id(tease §7-4). 계정이 없으므로 FK 아님.
    viewer_id   text    not null,
    -- 재집계로 클러스터가 사라져도 원문은 남고 소속만 풀린다.
    cluster_id  integer references question_clusters (id) on delete set null,
    created_at  timestamptz not null default now()
);
create index idx_questions_source  on questions (source_id);
create index idx_questions_cluster on questions (cluster_id);

-- ============================================================
-- question_likes — 좋아요. 클러스터가 아니라 **질문**에 붙는다(재집계에도 보존)
-- ============================================================
create table question_likes (
    id          integer generated by default as identity primary key,
    question_id integer not null references questions (id) on delete cascade,
    viewer_id   text    not null,
    created_at  timestamptz not null default now(),
    -- 🔴 같은 사람이 두 번 못 누른다. 이게 없으면 좋아요 순위가 새로고침 연타로 조작된다.
    unique (question_id, viewer_id)
);

-- ============================================================
-- embeddings — 질문 묶기와 구간 검색이 공유하는 벡터 저장소 (tease §5-3)
-- ============================================================
-- 테이블인 이유: 세그먼트·질문·클러스터 셋이 다 임베딩을 갖고, 모델을 바꾸면 셋을 다 다시 계산한다.
-- 벡터 DB·pgvector 없음 — N<1000 이라 numpy 코사인이 1ms 밑이다. 수만 개가 되면 pgvector 를 켠다.
create table embeddings (
    id          integer generated by default as identity primary key,
    kind        text    not null check (kind in ('segment', 'question', 'cluster')),
    -- kind 에 따라 다른 테이블을 가리켜서 FK 를 못 건다. 대상이 지워지면 고아가 남는데 검색 조인에서 자연히 빠진다.
    ref_id      integer not null,
    model       text    not null,
    dim         integer not null,
    -- float32 little-endian. numpy.frombuffer 로 바로 읽는다.
    vector      bytea   not null,
    created_at  timestamptz not null default now(),
    unique (kind, ref_id, model)
);

-- ============================================================
-- viewer_events — 유입 계측 (tease §9). append-only
-- ============================================================
-- "숏폼이 원본 유입을 늘린다"는 여기 쌓인 행 없이는 주장할 수 없다. 원본을 지워도 남는다.
create table viewer_events (
    id          integer generated by default as identity primary key,
    viewer_id   text    not null,
    source_id   integer references sources (id) on delete set null,
    clip_id     integer references clips (id) on delete set null,
    kind        text    not null check (kind in
                        ('short_play', 'short_complete', 'cta_click', 'origin_seek', 'origin_play', 'question_post', 'like')),
    -- 위치(초), 재생 길이 같은 부가 정보.
    payload     jsonb,
    created_at  timestamptz not null default now()
);
create index idx_events_source_kind on viewer_events (source_id, kind);
create index idx_events_clip on viewer_events (clip_id);
