-- 006 — 답하기가 겨룬 후보를 **대사와 함께** 남긴다. 2026-09-09.
--
-- 🔴 **왜 필요한가.** 답하기는 후보 셋을 만들어 판정하고 **시스템이 골라서** 렌더까지 해 버렸다.
-- 크리에이터에게는 클립 하나가 그냥 나온 것으로 보였고, 무엇과 겨뤘는지도 왜 그게 이겼는지도
-- 화면에 없었다. 판정 결과(O/X·점수)만 따로 보여주는 것도 답이 아니다 —
-- "조합, 2조각, 28초, 자립 X, 45점" 만 보고는 **고를 수가 없다.** 사람은 내용을 읽어야 판단한다.
--
-- 그래서 후보를 **대사 전문과 함께** 남기고, 무엇을 숏폼으로 만들지는 크리에이터가 고른다.
-- 판정은 사라지지 않고 **추천**이 된다(두 관문을 통과한 것 중 최고점).
--
-- 🔴 텍스트는 이미 그 시점에 있다. judge 는 영상이 아니라 **대사**를 보기 때문에 렌더 전에
-- 돌고(answers/judge.py 머리 주석), 그래서 후보마다 자른 대사가 이미 손에 있었다. 버리고 있었을 뿐이다.
--
-- parts 를 jsonb 로 두는 이유: 조각은 이 후보에 종속된 값이고 다른 데서 조인할 일이 없다.
-- 고른 뒤에는 `clip_parts` 로 옮겨 가고(1급 행), 그때부터 렌더·자막이 그걸 본다.

create table run_candidates (
    id          integer generated by default as identity primary key,
    run_id      integer not null references runs (id) on delete cascade,
    -- rank 가 낸 순서. 화면은 점수 순으로 다시 세우지만 원래 순서를 남겨 둔다.
    ordinal     integer not null,
    -- single(직접 답하는 한 덩어리) · combo(흩어진 답을 이어붙임) · tight(핵심만 짧게).
    -- 값을 CHECK 로 고정하지 않는다 — 후보 수를 늘리면 종류도 늘어난다(SHORTS_ANSWER_CANDIDATES).
    label       text,
    -- rank 가 왜 이렇게 잘랐는지.
    reason      text,
    -- 🔴 조각들. [{ordinal, segment_id, chunk_id, start_sec, end_sec,
    --              start_utterance_idx, end_utterance_idx, text}]
    -- **text 가 이 표의 존재 이유다** — 크리에이터가 읽고 고르는 것이 그것이다.
    parts       jsonb   not null,
    total_sec   double precision not null,
    -- judge 판정. 둘 다 참이어야 추천 대상이 된다.
    standalone  boolean,
    answers     boolean,
    score       integer,
    judge_note  text,
    -- 크리에이터가 [이걸로 만들기] 를 누른 시각. run 당 하나만 채워진다.
    chosen_at   timestamptz,
    created_at  timestamptz not null default now(),
    unique (run_id, ordinal),
    check (total_sec > 0)
);
create index idx_run_candidates_run on run_candidates (run_id);
