-- 007 — 관리자 기준. 2026-09-14.
--
-- 프롬프트를 네 층으로 나눈다(shorts_maker/standards.py 머리 주석).
--   1층 규칙 — 코드. 자립성 관문·출력 형식·번호 검증. 관리자에게 열지 않는다(깨지면 파싱이 실패한다)
--   2층 관리자 기준 — **이 표.** 채널이 공통으로 좋게 보는 것. 기준 경로와 질문 경로에 함께 들어간다
--   3층 영상 개요 — sources.context. 영상마다
--   4층 이번 요청 — 기준 입력 또는 시청자 질문
--
-- 🔴 **append-only.** 고칠 때마다 새 행을 넣고 읽을 때는 최신 행을 본다(clip_reviews 와 같은 방식).
-- 제자리 UPDATE 로 두면 "지난주 클립은 어떤 기준으로 뽑혔나" 에 답할 수 없다. 호출마다 프롬프트
-- 원문도 남지만(마이그레이션 005) 기준 자체의 변경 이력은 여기가 정본이다.
--
-- 빈 문자열은 "기준 없음" 이다. 지우고 싶으면 빈 행을 넣는다 — 행이 없는 것과 같게 읽는다.

create table admin_standards (
    id          integer generated by default as identity primary key,
    -- 🔴 1000자 상한. 이 글은 순위·후보·자르기·판정 **모든 호출에 붙는다.** 판정 프롬프트가
    -- 700~1000자라 기준이 그보다 길면 판정의 본문을 기준이 덮어 버린다. 실제로 적는 기준은
    -- 한두 문단(수백 자)이다.
    body        text    not null check (length(body) <= 1000),
    created_at  timestamptz not null default now()
);
